### ISSUE TITLE
parsing minor patch seems not working properly

### ISSUE THREAD

**Issue by silviucpp** [ua-parser/uap-cpp#18]
Hello,

For

```cpp
uap_cpp::UserAgent ua = uap_->parse("Parking Mania Free/1.9.5.2 CFNetwork/548.0.4 Darwin/11.0.0");
```

seems `ua.browser.patch_minor` it's empty instead 2. Not sure how the test's are passing as time in the test file there is a dedicated test with "Parking Mania Free/1.9.5.0 CFNetwork/548.0.4 Darwin/11.0.0" where patch_minor should be "0" not empty

Silviu

**Comment by asuhan** [comment]
Thanks, I'll look into it.

**Comment by asuhan** [comment]
I've attempted a fix on this branch: https://github.com/ua-parser/uap-cpp/tree/fix_patch_minor. It requires adding `- regex: '(ESPN) Radio (\d+)\.(\d+)\.?(\d+)? rv:(\d+) '` to the upstream `regexes.yaml`, alongside the existing `- regex: '(ESPN) Radio (\d+)\.(\d+)\.?(\d+)? ?[rv:]?(\d+)? '`, otherwise one of the `podcasting_user_agent_strings` tests fails. I'm not sure what flavor of regex is the original one, Boost doesn't consume `?[rv:]?(\d+)?` for `ESPN Radio 4.7.4 rv:1032 (iPhone; iPhone OS 9.2.1; en_US)`.

**Comment by silviucpp** [comment]
Hmm, do you plan to send a patch on the uap-core with the new regex or a better idea is to have a clone into uap-cpp, or another solution to have a file with this additional regex's and you merge with the core file at runtime?

**Comment by asuhan** [comment]
I think I'll end up asking a question or sending a PR to uap-core, but yes, patching at runtime is the other option.

**Comment by asuhan** [comment]
PR sent: https://github.com/ua-parser/uap-core/pull/305, once it's merged I'll be able to fix this cleanly.
